/**
 * Tripwire for the AI-facing documentation surface.
 *
 * public/llms.txt advertises stable URLs on rapidcam.app; the schema is served
 * from public/, and /docs + /examples are served by the aiDocsPlugin in
 * vite.config.ts straight from the repo's docs/ and examples/ directories.
 * This test maps every URL that llms.txt links to back to the repo file that
 * backs it, so a rename or deletion breaks the build instead of the published
 * contract.
 */

import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

const llmsTxt = readFileSync(join(repoRoot, "public", "llms.txt"), "utf8");

/** Repo file that backs a rapidcam.app path, per the serving setup. */
function backingFile(urlPath: string): string | null {
  if (urlPath === "/examples/index.json") return null; // generated by the plugin
  if (urlPath.startsWith("/schema/")) return join(repoRoot, "public", urlPath);
  if (urlPath.startsWith("/docs/")) return join(repoRoot, urlPath);
  if (urlPath.startsWith("/examples/")) return join(repoRoot, urlPath);
  return join(repoRoot, "public", urlPath);
}

describe("llms.txt contract", () => {
  const linked = [...llmsTxt.matchAll(/\]\((https:\/\/rapidcam\.app\/[^)]+)\)/g)].map(
    (m) => new URL(m[1]).pathname,
  );

  it("links to at least the format guide, schema, and examples index", () => {
    expect(linked).toContain("/docs/rcam-format-v2.md");
    expect(linked).toContain("/schema/rcam-v2.schema.json");
    expect(linked).toContain("/examples/index.json");
  });

  for (const path of linked) {
    const file = backingFile(path);
    if (file === null) continue;
    it(`serves ${path} from a file that exists`, () => {
      expect(existsSync(file)).toBe(true);
    });
  }

  it("examples directory is non-empty so /examples/index.json has content", () => {
    const examples = readdirSync(join(repoRoot, "examples")).filter((f) => f.endsWith(".rcam"));
    expect(examples.length).toBeGreaterThan(0);
  });
});
