/**
 * Builds the web-font catalogue the "Browse web fonts" picker searches:
 * `public/fonts/catalogue.json`, generated from the google/fonts repository.
 *
 * Run:  npx tsx scripts/build-font-catalogue.ts
 *
 * Why a committed snapshot rather than a live lookup? There is no index of
 * Google's families a browser can read: `fonts.google.com/metadata/fonts` sends
 * no CORS header, the repo is too large for jsDelivr's package listing (50 MB
 * cap), and the GitHub tree used below is a 7 MB response — none of which
 * belongs on the path of someone opening a font picker. Families appear a few
 * times a year, so a file regenerated by hand is current enough and costs the
 * app nothing at runtime.
 *
 * Two facts drive the shape of the output:
 *
 * 1. **TTF, never WOFF2.** `fonts.googleapis.com/css2` serves WOFF2, which is
 *    Brotli-compressed; the app's opentype.js has no decoder for it. The repo
 *    ships the original TTFs, and jsDelivr mirrors them with `access-control-
 *    allow-origin: *`, so the browser can fetch and parse them directly.
 *
 * 2. **A style is only offered when it has its own file.** A variable font is a
 *    single file covering a weight axis, and opentype.js renders its *default*
 *    instance — so listing "Bold" for one would hand back Regular outlines and
 *    cut the wrong thing. Variants are therefore deduped by filename: a
 *    variable family offers one entry, a static family offers the weights it
 *    actually ships.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const TREE_URL = "https://api.github.com/repos/google/fonts/git/trees/main?recursive=1";
const RAW = "https://cdn.jsdelivr.net/gh/google/fonts@main";
const OUT = "public/fonts/catalogue.json";

/** Parallel METADATA.pb fetches. Enough to finish in minutes, gentle on the CDN. */
const CONCURRENCY = 16;

interface TreeEntry {
  path: string;
}

/** One selectable font: a family/style pair backed by exactly one file. */
interface Variant {
  /** Style label shown to the user, e.g. "Regular", "Bold", "Bold Italic". */
  s: string;
  /** Path within the repo, e.g. "ofl/opensans/OpenSans[wdth,wght].ttf". */
  p: string;
}

interface Family {
  /** Display name, e.g. "Open Sans". */
  n: string;
  /** Category slug: sans-serif, serif, display, handwriting, monospace. */
  c: string;
  v: Variant[];
}

/** Weight numbers to the names a person recognises. */
const WEIGHT_NAMES: Record<number, string> = {
  100: "Thin",
  200: "ExtraLight",
  300: "Light",
  400: "Regular",
  500: "Medium",
  600: "SemiBold",
  700: "Bold",
  800: "ExtraBold",
  900: "Black",
};

function styleLabel(weight: number, style: string): string {
  const w = WEIGHT_NAMES[weight] ?? String(weight);
  const italic = style === "italic";
  if (w === "Regular") return italic ? "Italic" : "Regular";
  return italic ? `${w} Italic` : w;
}

/**
 * Pull the fields we need out of a METADATA.pb. It's a text-format protobuf, and
 * this reads the handful of keys that matter rather than pulling in a protobuf
 * parser for a build script: `name`, `category`, and each `fonts { … }` block's
 * weight/style/filename.
 */
function parseMetadata(text: string): { name: string; category: string; variants: Variant[] } | null {
  const name = /^name:\s*"([^"]+)"/m.exec(text)?.[1];
  if (!name) return null;
  const category = /^category:\s*"?([A-Z_]+)"?/m.exec(text)?.[1] ?? "SANS_SERIF";

  const variants: Variant[] = [];
  const seenFiles = new Set<string>();
  for (const block of text.matchAll(/fonts\s*\{([^}]*)\}/g)) {
    const body = block[1];
    const filename = /filename:\s*"([^"]+)"/.exec(body)?.[1];
    if (!filename || !filename.toLowerCase().endsWith(".ttf")) continue;
    // Fact 2 above: one file, one entry. A variable font's other weights are not
    // separate outlines, and offering them would be a lie.
    if (seenFiles.has(filename)) continue;
    seenFiles.add(filename);
    const weight = Number(/weight:\s*(\d+)/.exec(body)?.[1] ?? 400);
    const style = /style:\s*"([^"]+)"/.exec(body)?.[1] ?? "normal";
    variants.push({ s: styleLabel(weight, style), p: filename });
  }
  if (variants.length === 0) return null;
  return { name, category: category.toLowerCase().replace(/_/g, "-"), variants };
}

async function fetchText(url: string): Promise<string | null> {
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url);
      if (res.ok) return await res.text();
      if (res.status === 404) return null; // genuinely absent, don't retry
    } catch {
      /* transient — fall through to the retry */
    }
    await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
  }
  return null;
}

/** Run `work` over `items`, `CONCURRENCY` at a time, reporting progress. */
async function pooled<T, R>(items: T[], work: (item: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  let done = 0;
  const worker = async () => {
    while (next < items.length) {
      const i = next++;
      out[i] = await work(items[i]);
      if (++done % 100 === 0) process.stdout.write(`  ${done}/${items.length}\r`);
    }
  };
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  return out;
}

async function main(): Promise<void> {
  console.log("Fetching the google/fonts file tree…");
  const treeRes = await fetch(TREE_URL);
  if (!treeRes.ok) {
    throw new Error(
      `GitHub tree request failed (${treeRes.status}). Unauthenticated requests are ` +
        `rate-limited to 60/hour — wait, or set up a token and retry.`,
    );
  }
  const tree = (await treeRes.json()) as { tree: TreeEntry[]; truncated: boolean };
  if (tree.truncated) {
    // The API caps a tree response; a truncated one would silently drop families.
    throw new Error("GitHub returned a truncated tree — the repo outgrew a single request.");
  }

  const dirs = tree.tree
    .map((e) => e.path)
    .filter((p) => /^(ofl|apache|ufl)\/[^/]+\/METADATA\.pb$/.test(p))
    .map((p) => dirname(p));
  console.log(`${dirs.length} families found. Reading METADATA.pb for each…`);

  const parsed = await pooled(dirs, async (dir) => {
    const text = await fetchText(`${RAW}/${dir}/METADATA.pb`);
    if (!text) return null;
    const meta = parseMetadata(text);
    if (!meta) return null;
    return {
      n: meta.name,
      c: meta.category,
      v: meta.variants.map((v) => ({ s: v.s, p: `${dir}/${v.p}` })),
    } satisfies Family;
  });

  const families = parsed
    .filter((f): f is Family => f !== null)
    .sort((a, b) => a.n.localeCompare(b.n));
  const skipped = parsed.length - families.length;

  const catalogue = {
    generated: new Date().toISOString().slice(0, 10),
    source: "google/fonts@main",
    /** Prefix for every `p` below. Kept out of each entry — it's ~40 bytes × 4000. */
    cdn: `${RAW}/`,
    families,
  };

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(catalogue)}\n`);

  const variants = families.reduce((n, f) => n + f.v.length, 0);
  const kb = (Buffer.byteLength(JSON.stringify(catalogue)) / 1024).toFixed(0);
  console.log(
    `\nWrote ${OUT}: ${families.length} families, ${variants} selectable fonts, ${kb} KB` +
      (skipped ? ` (${skipped} skipped — no name or no TTF)` : ""),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
